### ISSUE TITLE
[TASK] Recipe Cards

### ISSUE THREAD

**Issue by mrogers23458** [Myuze/recipe-champion#9]
As a User,

I WANT to be able to view a recipe card based on my ingredients list,
SO THAT I can make recipes that use ingredients that I have on hand

**AC**
GIVEN a list of recipes in a word cloud
WHEN I click on the recipe
THEN I am presented with a recipe card

GIVEN a recipe card
WHEN I am viewing the recipe card
THEN I see the following information
-Recipe Name
-Ingredients
-a link to the recipe

**Comment by ghost** [comment]
Looks to be working
